apiVersion: v1
kind: Service
metadata:
  name: slave-jenkins-ubuntu-svc
  namespace: jenkins
  
spec:
  selector:
    app: slave-jenkins-ubuntu
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP

