apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave-jenkins-ubuntu
  namespace: jenkins
  labels:
    app: slave-jenkins-ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slave-jenkins-ubuntu
  template:
    metadata:
      labels:
        app: slave-jenkins-ubuntu
    spec:
      securityContext:
            fsGroup: 0
            runAsUser: 0
      serviceAccountName: jenkins-admin
      containers:
      - name: slave-jenkins-ubuntu
        image: kareemelkasaby/jenkins-slave-java-11
        imagePullPolicy: Always
        ports:
        - containerPort: 22
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
              
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
